### ISSUE TITLE
iconv cannot be found

### ISSUE THREAD

**Issue by Aussieboy11** [brck/CrisisStack#1]
When running the given script (under "Required Extensions"), the following error comes up:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php5-intl' instead of 'php5-idn'
Note, selecting 'php5-common' instead of 'php5-mhash'
Note, selecting 'php5-common' instead of 'php5-json'
Package iconv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'iconv' has no installation candidate
```

The installation then stops.  Removing "iconv" from the script allows everything else to install.

**Comment by Aussieboy11** [comment]
A site online says that iconv is built into php5-cgi.  Perhaps that is the package that needs to be installed instead?

**Comment by rasmi** [comment]
There is no need to install iconv (at least for me on `2015-05-05-raspbian-wheezy.img`). Running `iconv -l` shows it is already installed.

**Comment by Onuonga** [comment]
Closed as it is expected that you are using the latest version of raspbian
