### ISSUE TITLE
Installation cannot be completed headlessly on Pi

### ISSUE THREAD

**Issue by Aussieboy11** [brck/CrisisStack#2]
How can the installation script be run when using a Raspberry Pi in headless mode?

**Comment by Onuonga** [comment]
If you know the IP address of the PI you will need to SSH into it. For the most part most images come with a default username of "pi" and password "raspberry"
Therefore this should allow you to SSH in from your terminal or terminal emulator with the command "ssh pi@<YOUR-PI-IP-ADDRESS>"  where 'pi' is the username.

**Comment by Aussieboy11** [comment]
Yes, I've done that.  For the "Run the Install Script" step, though, it says to "point your browser to the base URL of your raspberry pi".  Is that also possible via ssh?  Am I missing something?

**Comment by Onuonga** [comment]
So to do that, if you are on the same network as your PI which I assume you are because you are able to SSH in, you should be able to load the page from your computers web browser. All you need to do is ppu the IP of you PI on the web browser of choice.
