### ISSUE TITLE
deploying (and updating) with resin.io

### ISSUE THREAD

**Issue by alexandrosm** [brck/CrisisStack#3]
Hi there, I am wondering if the CrisisStack team is interested in adapting the project to be deployed via resin.io. In practice this will mean a much simpler installation process, and the devices, once online, will be able to be managed, debugged and updated remotely. 

I'm the CEO of resin.io and if this is of interest to you we can find a way to make it work so ignore the pricing page to begin with, we're very eager to be of help to this project.

**Comment by Onuonga** [comment]
As of now, because this is an open source project, we need to ensure that we are open with regards to the way we do things. We will put it as one of the options for customers to use but we can not have it as the only one.
