### ISSUE TITLE
Deleting Apps

### ISSUE THREAD

**Issue by srutto** [brck/CrisisStack#5]
Steps to Reproduce
1. Go to 'My Applications'
2. Select Crowdmap
3. Click on the 'Delete App' button at the bottom of the page

Expected Outcome
On clicking 'Delete App', the user should confirm the delete action before proceeding. On confirmation to delete, the application should be uninstalled and deleted from 'My Applications'. The user should be able to find it in the 'Application Store' where it can be re-installed.

Actual Outcome
On clicking 'Delete App', the button says 'Deleting' and the deleting gif keeps spinning, but nothing happens. In the case of BitTorrent Sync, the user is redirected to the homepage on clicking 'Delete App'.

@Onuonga:
Action Items:
1. Add confirm to delete action. When a user clicks on the delete button, s/he should confirm whether or not to perform the action. This is because sometimes a user can accidentally click on it.
2. Ensure apps are uninstalled and deleted from 'My Applications' when a user deletes them. The apps should move to 'Application store' where the administrator can re-install them.

**Comment by Onuonga** [comment]
Cross checked the functionality and it seems that I was not disabling the site according to Nginx standards. This has been fixed.
