### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by srutto** [brck/CrisisStack#6]
Steps to Reproduce
1. Select 'Login' on the menu
2. Enter username and password then click on 'Login'

Expected Outcome
User should be redirected to the home page with administrator privileges.

Actual  Outcome
User is redirected to http://crisisstack.com/login with an internal server error
![tinygrab screen shot 10-7-15 11 37 42 am](https://cloud.githubusercontent.com/assets/1751822/10332741/f75d7770-6ce7-11e5-86c7-cc49730443bd.png)

**Comment by Onuonga** [comment]
Fixed. I was writing my loops badly. Python expects you to realize you need to do your indentation well. Clearly I did not.
